class Profile {
  String nickname,
      name,
      cellno,
      email,
      telno,
      faxno,
      bkc,
      blc,
      cac,
      bli,
      blp,
      lcc,
      ivi,
      txi,
      ftc,
      dgc,
      dln,
      vsc,
      tsc,
      doc,
      empGB;
  int profile_seq, icon, maxseq;

  Profile.fromJson(Map<String, dynamic> json)
      : profile_seq = json['SEQ'],
        nickname = json['NICKNAME'].toString(),
        name = json['NAME'].toString(),
        cellno = json['CELLNO'] ?? '',
        email = json['EMAIL'] ?? '',
        telno = json['TELNO'] ?? '',
        faxno = json['FAXNO'] ?? '',
        icon = json['ICON'],
        maxseq = json['MAXSEQ'],
        bkc = json['BKC'] ?? 'NNN',
        blc = json['BLC'] ?? 'NNN',
        cac = json['CAC'] ?? 'NNN',
        bli = json['BLI'] ?? 'NNN',
        blp = json['BLP'] ?? 'NNN',
        lcc = json['LCC'] ?? 'NNN',
        ivi = json['IVI'] ?? 'NNN',
        txi = json['TXI'] ?? 'NNN',
        ftc = json['FTC'] ?? 'NNN',
        dgc = json['DGC'] ?? 'NNN',
        dln = json['DLN'] ?? 'NNN',
        vsc = json['VSC'] ?? 'NNN',
        tsc = json['TSC'] ?? 'NNN',
        doc = json['DOC'] ?? 'NNN',
        empGB = json['EMPGB'] ?? 'C';
}
