class User {
  final String userid,
      status,
      pwd1,
      pwd2,
      nacd,
      bkport,
      bkportnm,
      regno,
      custnm,
      custcd,
      custaddr,
      custgb,
      nickname,
      username,
      cellno,
      email,
      telno,
      faxno,
      inpdate,
      upddate,
      confirmuser,
      confirmdate,
      talkrcvdelay,
      talkrcvbkcfm,
      talkrcvblmod,
      talkrcvblisu,
      talkrcvivisu,
      talkrcvftcfm,
      talkrcvan,
      mailrcvdelay,
      mailrcvbkcfm,
      mailrcvblmod,
      mailrcvblisu,
      mailrcvivisu,
      mailrcvftcfm,
      mailrcvan,
      delayaddress,
      bkcfmaddress,
      blmodaddress,
      blisuaddress,
      ivisuaddress,
      ftcfmaddress,
      roles,
      stpass,
      edpass,
      logindate,
      prohibitautoinvoice,
      responseMsg,
      dashboard,
      valid;
  int icon;

  User.fromJson(Map<String, dynamic> json)
      : userid = json['USERID'].toString(),
        status = json['STATUS'].toString(),
        pwd1 = json['PWD1'].toString(),
        pwd2 = json['PWD2'].toString(),
        nacd = json['NACD'].toString(),
        bkport = json['BKPORT'].toString(),
        bkportnm = json['BKPORTNM'].toString(),
        regno = json['REGNO'].toString(),
        custnm = json['CUSTNM'].toString(),
        custcd = json['CUSTCD'].toString(),
        custaddr = json['CUSTADDR'].toString(),
        custgb = json['CUSTGB'].toString(),
        nickname = json['NICKNAME'].toString(),
        username = json['USERNAME'].toString(),
        cellno = json['CELLNO'].toString(),
        email = json['EMAIL'].toString(),
        telno = json['TELNO'].toString(),
        faxno = json['FAXNO'].toString(),
        icon = json['ICON'],
        inpdate = json['INPDATE'].toString(),
        upddate = json['UPDDATE'].toString(),
        confirmuser = json['CONFIRMUSER'].toString(),
        confirmdate = json['CONFIRMDATE'].toString(),
        talkrcvdelay = json['TALKRCVDELAY'].toString(),
        talkrcvbkcfm = json['TALKRCVBKCFM'].toString(),
        talkrcvblmod = json['TALKRCVBLMOD'].toString(),
        talkrcvblisu = json['TALKRCVBLISU'].toString(),
        talkrcvivisu = json['TALKRCVIVISU'].toString(),
        talkrcvftcfm = json['TALKRCVFTCFM'].toString(),
        talkrcvan = json['TALKRCVAN'].toString(),
        mailrcvdelay = json['MAILRCVDELAY'].toString(),
        mailrcvbkcfm = json['MAILRCVBKCFM'].toString(),
        mailrcvblmod = json['MAILRCVBLMOD'].toString(),
        mailrcvblisu = json['MAILRCVBLISU'].toString(),
        mailrcvivisu = json['MAILRCVIVISU'].toString(),
        mailrcvftcfm = json['MAILRCVFTCFM'].toString(),
        mailrcvan = json['MAILRCVAN'].toString(),
        delayaddress = json['DELAYADDRESS'].toString(),
        bkcfmaddress = json['BKCFMADDRESS'].toString(),
        blmodaddress = json['BLMODADDRESS'].toString(),
        blisuaddress = json['BLISUADDRESS'].toString(),
        ivisuaddress = json['IVISUADDRESS'].toString(),
        ftcfmaddress = json['FTCFMADDRESS'].toString(),
        roles = json['ROLES'].toString(),
        stpass = json['STPASS'].toString(),
        edpass = json['EDPASS'].toString(),
        logindate = json['LOGINDATE'].toString(),
        prohibitautoinvoice = json['PROHIBITAUTOINVOICE'].toString(),
        responseMsg = json['RESPONSE_MSG'].toString(),
        dashboard = json['DASHBOARD'].toString(),
        valid = json['VALID'].toString();
}
