class BookingSchedule {
  String gb,
      svc,
      vsl,
      vslnm,
      vyg,
      span,
      pol,
      polnm,
      polw,
      polwnm,
      pod,
      podnm,
      podw,
      podwnm,
      etd,
      eta,
      docudate,
      cntrdate;
  String vgmclosing,
      afrclosing,
      mainempinfo,
      subempinfo,
      mrn,
      callsgn,
      vslnacd,
      dtmlincount,
      atmlincount,
      dtmlvslvygcd,
      atmlvslvygcd,
      tmlremark;
  int mainempgender, subempgender;

  BookingSchedule.fromJson(Map<String, dynamic> json)
      : gb = json['GB'] ?? '',
        svc = json['SVC'] ?? '',
        vsl = json['VSL'] ?? '',
        vslnm = json['VSLNM'] ?? '',
        vyg = json['VYG'] ?? '',
        span = json['SPAN'] ?? '',
        pol = json['POL'] ?? '',
        polnm = json['POLNM'] ?? '',
        polw = json['POLW'] ?? '',
        polwnm = json['POLWNM'] ?? '',
        pod = json['POD'] ?? '',
        podnm = json['PODNM'] ?? '',
        podw = json['PODW'] ?? '',
        podwnm = json['PODWNM'] ?? '',
        etd = json['ETD'] ?? '',
        eta = json['ETA'] ?? '',
        docudate = json['DOCUDATE'] ?? '',
        cntrdate = json['CNTRDATE'] ?? '',
        vgmclosing = json['VGMCLOSING'] ?? '',
        afrclosing = json['AFRCLOSING'] ?? '',
        mainempgender = json['MAINEMPGENDER'] ?? 0,
        mainempinfo = json['MAINEMPINFO'] ?? '',
        subempgender = json['SUBEMPGENDER'] ?? 0,
        subempinfo = json['SUBEMPINFO'] ?? '',
        mrn = json['MRN'] ?? '',
        callsgn = json['CALLSGN'] ?? '',
        vslnacd = json['VSLNACD'] ?? '',
        dtmlincount = json['DTMLINCOUNT'] ?? '',
        atmlincount = json['ATMLINCOUNT'] ?? '',
        dtmlvslvygcd = json['DTMLVSLVYGCD'] ?? '',
        atmlvslvygcd = json['ATMLVSLVYGCD'] ?? '',
        tmlremark = json['TMLREMARK'] ?? '';
}
